name: 'Setup Swift'
description: 'Set up a specific version of swift using swiftenv'
inputs:
  swift-version:
    description: 'Exact version of a Swift version to use.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install swiftenv
      shell: bash
      run: |
        export SWIFTENV_ROOT="${{ github.action_path }}/swiftenv"
        export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"

        git clone --depth 1 https://github.com/kylef/swiftenv.git $SWIFTENV_ROOT

        echo "SWIFTENV_ROOT=$SWIFTENV_ROOT" >> $GITHUB_ENV
        echo "$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims" >> $GITHUB_PATH
    - name: Install swift
      shell: bash
      run: swiftenv install -s ${{ inputs.swift-version }}
