name: "Tests"
on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'action.yml'
      - 'dist/**'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'action.yml'
      - 'dist/**'

jobs:
  # test action works running from the graph
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-18.04", "ubuntu-20.04", "macos-10.15"]
        swift-version: ["5.0.3", "5.1.5", "5.2.5", "5.3.3", "5.4.2"]
        exclude:
          - operating-system: "ubuntu-20.04"
            swift-version: "5.0.3"
          - operating-system: "ubuntu-20.04"
            swift-version: "5.1.5"
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          swift-version: ${{ matrix.swift-version }}
      - run: echo $PATH
      - run: which swift
      - run: swift -version
